version: '3.8'
services:
  mongo:
    image: mongo:4.4.0-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mongo-books-example:latest
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      - mongo
    environment:
      - spring.profiles.active=integration
      - MONGODB_URI=mongodb://admin:secret@mongo:27017/votes_db?authSource=admin
