

api:
  swagger:
    title: Springfox Swagger Contest Example
    description: This application provides an example of how to provide extra swagger and
      springfox configuration in order to better document the API.
    version: v1
    contact:
      name: Jim Stafford
      url: https://webdev.jhuep.com/~jcs/ejava-springboot

  controllers:
    ContestControllers:
      getContests:
        description: This endpoint will return a collection of contests based
          on the paging values assigned
        param:
          offset: optional, server will set to "no offset" if not supplied or 0
          limit: optional, server will set to "no limit" if not supplied or 0

  model:
    ContestListDTO:
      count: The number of elements in the contest field.
      keywords: Used as a description of the query used to obtain the contests.
      limit: Maximum number of elements the page was originally requested to have.
      offset: Offset from the beginning of the collection of contests on the server.
      total: Total number of contests that are available, that matched the original
        query but may not have been returned because of paging limits set.