version: '3.8'
services:
  mongo:
   image: mongo:4.4.0-bionic
   environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: secret
  api:
    build:
      context: .
      dockerfile: Dockerfile.layered
    image: docker-hello-example:layered
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      - mongo
      - postgres
    environment:
      - spring.profiles.active=integration
      - MONGODB_URI=mongodb://admin:secret@mongo:27017/votes_db?authSource=admin
      - DATABASE_URL=postgres://postgres:secret@postgres:5432/postgres
